language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install python-dateutil
  - pip install pytz
  - pip install lxml
  - pip install aiofiles
  - pip install asyncio-contextmanager
  - pip install pytest --upgrade
  - pip install pytest-asyncio
  - pip install cryptography
# command to run tests
script: pytest -v
